#!/usr/bin/env python3
"""Build protocol/src/main/resources/.../registry-ids.txt: network IDs of registry entries packet codecs need.

Lines: `<registry> <entry> <first protocol>=<id|-> ...`, compressed to change points like packet-ids.txt.
Source: registries.json from Mojang's data generator (reports.py). Versions without the report or entry get `-`.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch import CACHE  # noqa: E402
from versions import RELEASES  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[2] / "protocol/src/main/resources/ru/cororo/authserver/protocol/registry-ids.txt"
ENTRIES = {
    "minecraft:menu": [f"minecraft:generic_9x{rows}" for rows in range(1, 7)],
    "minecraft:data_component_type": ["minecraft:custom_name", "minecraft:lore"],
}


def main():
    reports = {}
    for protocol, release, _ in RELEASES:
        path = CACHE / release / "reports" / "registries.json"
        reports[protocol] = json.loads(path.read_text()) if path.exists() else {}
    lines = ["# Generated by tools/vanilla/registry_ids.py - do not edit.",
             "# <registry> <entry> <first protocol>=<id|-> ..."]
    for registry, entries in ENTRIES.items():
        for entry in entries:
            points, previous = [], None
            for protocol, _, _ in RELEASES:
                value = reports[protocol].get(registry, {}).get("entries", {}).get(entry, {}).get("protocol_id")
                if value != previous:
                    points.append(f"{protocol}=" + ("-" if value is None else str(value)))
                    previous = value
            lines.append(f"{registry} {entry} {' '.join(points)}")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
