package ru.cororo.authserver.storage

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection

enum class DatabaseType { SQLITE, H2, POSTGRESQL }

/**
 * @property file database file for SQLite (`auth.db`) and H2 (`auth`, the `.mv.db` suffix is added by H2)
 * @property tablePrefix prefix for every table, allowing several servers to share one PostgreSQL database
 */
data class DatabaseConfig(
    val type: DatabaseType = DatabaseType.SQLITE,
    val file: String = "data/auth.db",
    val host: String = "localhost",
    val port: Int = 5432,
    val database: String = "authserver",
    val user: String = "authserver",
    val password: String = "",
    val poolSize: Int = 4,
    val tablePrefix: String = "authserver_",
) {
    init {
        require(tablePrefix.matches(Regex("[A-Za-z0-9_]*"))) { "Table prefix may only contain letters, digits and '_'" }
    }
}

/** Connection pool plus schema management. Close it on shutdown. */
class Database(private val config: DatabaseConfig) : AutoCloseable {
    private val logger = LoggerFactory.getLogger(Database::class.java)
    internal val dialect = Dialect.of(config.type)
    private val dataSource = HikariDataSource(hikariConfig())

    val accounts: AccountRepository = JdbcAccountRepository(this, config.tablePrefix)

    init {
        migrate()
    }

    internal fun <T> connection(block: (Connection) -> T): T = dataSource.connection.use(block)

    private fun hikariConfig() = HikariConfig().apply {
        poolName = "authserver-db"
        when (config.type) {
            DatabaseType.SQLITE -> {
                Path.of(config.file).toAbsolutePath().parent?.let(Files::createDirectories)
                jdbcUrl = "jdbc:sqlite:${config.file}"
                driverClassName = "org.sqlite.JDBC"
                // SQLite serialises writers; one connection avoids SQLITE_BUSY under load.
                maximumPoolSize = 1
                connectionInitSql = "PRAGMA journal_mode=WAL"
            }
            DatabaseType.H2 -> {
                Path.of(config.file).toAbsolutePath().parent?.let(Files::createDirectories)
                jdbcUrl = "jdbc:h2:file:${Path.of(config.file).toAbsolutePath()};DB_CLOSE_ON_EXIT=FALSE"
                driverClassName = "org.h2.Driver"
                maximumPoolSize = config.poolSize
            }
            DatabaseType.POSTGRESQL -> {
                jdbcUrl = "jdbc:postgresql://${config.host}:${config.port}/${config.database}"
                driverClassName = "org.postgresql.Driver"
                username = config.user
                password = config.password
                maximumPoolSize = config.poolSize
            }
        }
    }

    /** Applies pending migrations in order; each one runs in its own transaction. */
    private fun migrate() = connection { connection ->
        val versions = "${config.tablePrefix}schema_version"
        connection.createStatement().use { it.execute("CREATE TABLE IF NOT EXISTS $versions (version INTEGER NOT NULL)") }
        val current = connection.createStatement().use { statement ->
            statement.executeQuery("SELECT MAX(version) FROM $versions").use { if (it.next()) it.getInt(1) else 0 }
        }
        val migrations = Migrations.all(dialect, config.tablePrefix)
        for ((index, statements) in migrations.withIndex().drop(current)) {
            connection.autoCommit = false
            try {
                connection.createStatement().use { statement -> statements.forEach(statement::execute) }
                connection.prepareStatement("INSERT INTO $versions (version) VALUES (?)").use {
                    it.setInt(1, index + 1)
                    it.executeUpdate()
                }
                connection.commit()
                logger.info("Applied database migration {}", index + 1)
            } catch (exception: Exception) {
                connection.rollback()
                throw exception
            } finally {
                connection.autoCommit = true
            }
        }
    }

    override fun close() = dataSource.close()
}

/** SQL differences between the supported databases. */
internal enum class Dialect(val identityColumn: String) {
    SQLITE("INTEGER PRIMARY KEY AUTOINCREMENT"),
    H2("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    POSTGRESQL("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");

    companion object {
        fun of(type: DatabaseType) = when (type) {
            DatabaseType.SQLITE -> SQLITE
            DatabaseType.H2 -> H2
            DatabaseType.POSTGRESQL -> POSTGRESQL
        }
    }
}

/** Schema history. Never edit a released migration; append a new one instead. */
internal object Migrations {
    fun all(dialect: Dialect, prefix: String): List<List<String>> = listOf(
        listOf(
            """
            CREATE TABLE ${prefix}accounts (
                id ${dialect.identityColumn},
                username VARCHAR(16) NOT NULL,
                username_lower VARCHAR(16) NOT NULL UNIQUE,
                password_hash VARCHAR(512),
                premium SMALLINT NOT NULL DEFAULT 0,
                premium_uuid VARCHAR(36),
                registered_at BIGINT NOT NULL,
                registration_ip VARCHAR(45),
                last_login_at BIGINT,
                last_login_ip VARCHAR(45)
            )
            """.trimIndent(),
            "CREATE INDEX ${prefix}accounts_registration_ip ON ${prefix}accounts (registration_ip)",
            "CREATE INDEX ${prefix}accounts_premium_uuid ON ${prefix}accounts (premium_uuid)",
        ),
        // Email and two-factor authentication.
        listOf(
            "ALTER TABLE ${prefix}accounts ADD COLUMN email VARCHAR(254)",
            "ALTER TABLE ${prefix}accounts ADD COLUMN two_factor VARCHAR(8) DEFAULT 'NONE' NOT NULL",
            "ALTER TABLE ${prefix}accounts ADD COLUMN totp_secret VARCHAR(64)",
        ),
    )
}
